FROM    ubuntu:focal
ENV     OPAMROOTISOK=1
RUN     apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        opam make pkg-config cargo libhidapi-dev libev-dev libgmp-dev libffi-dev \
        python3-pip
RUN     opam init --disable-sandboxing --bare
RUN     pip3 install jsonschema

ADD     . /build
WORKDIR /build
RUN     make
