name:                ligo-webide
version:             0.1.0.0
github:              "serokell/ligo-webide"
license:             BSD3
copyright:           "2022 Serokell"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ligo-webide-backend:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ligo-webide
    - servant
