(library
 (name simple_jsligo_test)
 (public_name ligo.lsp_test.error_recovery.simple_jsligo_test)
 (inline_tests
  (deps
   (glob_files *.jsligo)
   (glob_files original/*.jsligo))
  (libraries
   bls12-381.archive
   octez-rustzcash-deps
   octez-riscv-pvm
   octez-rust-deps)
  (executable
   (flags
    (:standard -cclib "-lblst" -cclib "-loctez_rustzcash_deps"))))
 (libraries error_recovery)
 (preprocess
  (pps ppx_jane)))
