## LSP and Debugger

include:
  - '/.ci/.gitlab-ci-tools-common.yml'

variables:
  OCTEZ_VERSION: "v16.1"

vscode-extension-test:
  stage: tools-check
  rules: &vscode_extension_mr_dev
    - !reference [.vscode_extension_mr_changes]
    - !reference [.dev]
  needs: [docker_extract, debugger-build]
  script:
    - docker build --build-arg OCTEZ_VERSION="$OCTEZ_VERSION" -f tools/vscode/Dockerfile -t lsp-vscode-test:$CI_JOB_ID .
    - docker run --rm --init --user vscode lsp-vscode-test:$CI_JOB_ID xvfb-run bash -c 'yarn && yarn run package && yarn run test'
  after_script:
    - docker image rm lsp-vscode-test:$CI_JOB_ID

vscode-extension-extest:
  stage: tools-check
  rules: *vscode_extension_mr_dev
  needs: [docker_extract, debugger-build]
  script:
    - docker build --build-arg OCTEZ_VERSION="$OCTEZ_VERSION" -f tools/vscode/Dockerfile -t lsp-vscode-test:$CI_JOB_ID .
    - docker run --rm --init --user vscode lsp-vscode-test:$CI_JOB_ID xvfb-run bash -c 'yarn && yarn run package && yarn run extest'
  after_script:
    - docker image rm lsp-vscode-test:$CI_JOB_ID

vscode-extension-extest-deploy:
  stage: tools-check
  rules: *vscode_extension_mr_dev
  needs: [docker_extract, debugger-build]
  script:
    - docker build --build-arg OCTEZ_VERSION="$OCTEZ_VERSION" -f tools/vscode/Dockerfile -t lsp-vscode-test:$CI_JOB_ID .
    - docker run --rm --init --user vscode lsp-vscode-test:$CI_JOB_ID xvfb-run bash -c 'yarn && yarn run package && yarn run extest-deploy'
  after_script:
    - docker image rm lsp-vscode-test:$CI_JOB_ID
  allow_failure: true

emacs-lsp-client-test:
  stage: tools-check
  tags:
    - docker
  image: silex/emacs:27.2-ci-cask
  variables:
    EMACS: "emacs-27.2"
  rules:
    - !reference [.dev]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
      - tools/emacs/**/*
  needs: [docker_extract]
  script:
    # Add ligo to path
    - export PATH=$PWD:$PATH
    - cd tools/emacs
    - cask install
    - cask emacs --batch -L . -l tests/configuration-test.el -f ert-run-tests-batch

vscode-extension:
  stage: tooling
  rules:
    - !reference [.vscode_extension_mr_changes]
    - !reference [.dev]
    - !reference [.vscode_production]
  needs: [debugger-build, debugger-build-macos]
  tags:
    - docker
  image: node:18-buster
  script:
    - mkdir -p tools/vscode/bin
    - cp -r Linux tools/vscode/bin
    - cp -r Darwin tools/vscode/bin
    - cd tools/vscode
    - mv ligo-debugger-platform-dispatcher.sh bin/ligo-debugger
    - make package
  artifacts:
    paths:
      - ./tools/vscode/*.vsix

vscode-extension-publish:
  stage: push
  rules:
    - !reference [.vscode_production]
  needs: [vscode-extension]
  tags:
    - docker
  image: node:18-buster
  when: manual
  script:
    - yarn global add @vscode/vsce ovsx
    - vsce publish --packagePath ./tools/vscode/*.vsix # Uses VSCE_PAT env variable as personal access token
    - ovsx publish ./tools/vscode/*.vsix # Uses OVSX_PAT env variable as personal access token
