;; Library exporting the TypeScript CST and our AST

(library
 (name typescript_ast)
 (modules ast ts_wrap loc_map lexeme number ast_stripped)
 (libraries
  tree_sitter
  tree_sitter_typescript
  simple-utils ;; For source regions ([Region])
  cst_shared ;; For printing the TS CST ([Print_cst])
             ;;  cst_jsligo ;; For mapping the TS CST to JsLIGO CST
  lexing_shared ;; For metadata ([Wrap])
  hex
  zarith
  core
  core_kernel.nonempty_list))

;; Standalones

(executable
 (name print_cst_main)
 (libraries typescript_ast)
 (modules print_cst print_cst_main))

(executable
 (name decode_main)
 (libraries typescript_ast)
 (modules decode decode_main))

(executable
 (name strip_main)
 (libraries typescript_ast)
 (modules decode strip strip_main))

;; Local build of a standalone parser for node-types.json

(executable
 (name static_nodes_reader)
 (libraries
  cst_shared ;; For printing the TS CST
  core
  core_kernel.nonempty_list
  yojson)
 (modules static_nodes_reader))

;; Lexer for numbers

(ocamllex number)
