(* This module defines the syntax errors when printing the CST *)

(* Errors *)

type t =
  (* Keywords *)
  | Infer
  | Keyof
  | Meta
  | Target
  | False
  | True
  | Super
  | Null
  | Satisfies
  | Yield
  | New
  | Instanceof
  | Implements
  | Assert
  | As
  | Async
  | Function
  | Override
  | Readonly
  | Public
  | Private
  | Protected
  | Set
  | Get
  | Static
  | This
  | Is
  | Class
  | Const
  | Let
  | Undefined
  | Abstract
  | Declare
  | Accessor
  | Global
  | Module
  | Enum
  | Import
  | Interface
  | Extends
  | Namespace
  | Type
  | Using
  | Return
  | Switch
  | Case
  | Default
  | Throw
  | While
  | With
  | Any
  | Number
  | Boolean
  | String
  | Symbol
  | Unique_symbol
  | Void
  | Unknown
  | Never
  | Object
  | Asserts
  | Debugger
  | Break
  | Continue
  | Do
  | Export
  | For
  | From
  | Await
  | Var
  | In
  | Of
  | If
  | Else
  | Typeof
  | Try
  | Catch
  | Require
  | Delete
  | Finally
  (* Symbols *)
  | Left_brace
  | Right_brace
  | Left_chevron
  | Right_chevron
  | Left_bracket
  | Right_bracket
  | Left_parenthesis
  | Right_parenthesis
  | Asterisk
  | Equal
  | Strict_equal
  | Question_mark
  | Plus_equal
  | Minus_equal
  | Mult_equal
  | Div_equal
  | Rem_equal
  | Xor_equal
  | And_equal
  | Or_equal
  | Right_shift_equal
  | Unsigned_shift_right_equal
  | Left_shift_equal
  | Exponent_equal
  | Conjunction_equal
  | Disjunction_equal
  | Non_null_equal
  | Exclamation_mark
  | Tilde
  | Minus
  | Plus
  | Conjunction
  | Disjunction
  | Right_shift
  | Unsigned_shift_right
  | Left_shift
  | Xor
  | Or
  | Div
  | Rem
  | Exponent
  | Less_than
  | Less_than_or_equal
  | No_conv_equal
  | Different
  | No_conv_different
  | Greater_than_or_equal
  | Greater_than
  | Non_null
  (* Syntax errors *)
  | Expression
  | Export_clause
  | Export_clause_or_all
  | Named_imports_or_all_or_id
  | Named_imports_or_all
  | Type_or_conjunction
  | Type_or_disjunction
  | File_path
  | Identifier_or_string
  | Identifier
  | Parenthesized_expression
  | Statement
  | Switch_body
  | Initial_assignment
  | Expression_or_semicolon
  | In_or_of
  | Block
  | Label
  | Function_name
  | Parameters
  | Class_name
  | Class_body
  | Let_or_const
  | Variable
  | Type_annotation
  | Module_name
  | Module_declaration
  | Namespace_name
  | Namespace_declaration
  | Type_name
  | Type_expression
  | Type_parameter
  | Enumeration_name
  | Enumeration
  | Interface_name
  | Interface_body
  | Augmented_assignment
  | Unary_operator
  | Binary_operator
  | Type_arguments
  | Property_identifier
  | Property_name
  | Block_or_expression
  | Arguments
  | Member_or_call
  | Member_expression
  | Identifier_or_member
  | Type_identifier_or_path
  | Identifier_or_rest
  | Object_denotation
  | Type_or_string_or_number
  | Function_denotation
  | Identifier_or_type
  | Pattern
  | Identifier_or_path
  | Type_or_typeof
  | New_or_import
  | Target_or_meta
  | String_literal
  | Regexp
  | Number_literal
  | Namespace_export
  | Import_clause
  | Namespace_or_named_imports
  | Namespace_or_named_imports_or_ident
  | Namespace_import
  | Named_imports
  | Import_specifier
  | Import_require_clause
  | Import_attribute
  | For_or_await
  | Empty_statement
  | Declaration
  | Function_declaration
  | Generator_function_declaration
  | Class_declaration
  | Async_or_function
  | Const_or_type_name
  | Const_or_enum
  | Glimmer_template
  | Using_or_expression
  | LHS_of_augmented_assgmnt
  | Template_string
  | Object_expression
  | Key_value_pair
  | Array
  | Type_parameters
  | Spread
  | Function_expression
  | Arrow_function
  | Generator_function
  | Class_expression
  | Extends_or_implements
  | Implements_clause
  | Extends_clause
  | Method_definition
  | Static_block
  | Abstract_method_signature
  | Public_field_definition
  | Meta_property
  | Call_expression
  | Non_null_expression
  | Parenthesized_type
  | Predefined_type
  | Nested_type_identifier
  | Generic_type
  | Object_type
  | Property_signature
  | Call_signature
  | Asserts_annotation
  | Type_predicate_annotation
  | Construct_signature
  | Index_signature
  | Mapped_type_signature
  | Omitting_type_annotation
  | Adding_type_annotation
  | Opting_type_annotation
  | Method_signature
  | Array_type
  | Tuple_type
  | Tuple_parameter
  | Optional_tuple_parameter
  | Rest_pattern
  | Optional_type
  | Rest_type
  | Type_query
  | Type_query_subscript
  | Type_query_member
  | Type_query_instantiation
  | Type_query_call
  | Index_type_query
  | Existential_type
  | Literal_type
  | Lookup_type
  | Conditional_type
  | Template_literal_type
  | Intersection_type
  | Union_type
  | Function_type
  | Type_predicate
  | Readonly_type
  | Constructor_type
  | Required_parameter
  | Decorator
  | Decorator_member
  | Decorator_call
  | Parenthesized_decorator
  | Public_private_protected
  | Object_pattern
  | Pair_pattern
  | Assignment_pattern
  | Computed_property_name
  | Object_assignment_pattern
  | Array_pattern
  | Let_or_const_or_var
  | Const_or_type
  | Optional_chain
  | Index_expression
  | Object_field
  | Array_cell
  | Class_member
  | Import_or_expression
  | Argument
  | Object_type_field
  | Asserted
  | Type_of_index_signature
  | Plus_or_minus
  | Parameter
  | Object_pattern_field
  | Value_of_pair_pattern
  | Object_or_array_pattern
  | Array_cell_pattern
  | Increment
  | Decrement
  | Backquote
  | Colon
  | Ellipsis
  | Arrow
  | Dot
  | And
  | Vertical_bar
  | Incr_or_decr_or_expr
  | Increment_or_decrement
  | Block_or_ident_or_decl
  | Type_alias_declaration
  | Variable_declaration
  | String_or_type
  | Selector_or_optional_chain
  | Syntax_error

type error = t

val to_string : error -> string
