#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE[0]}")"
ROOT_PATH=".."

DEB_PKG_URL=$1
CURRENT_VERSION=$2

PKGBUILD_FOLDER_PATH="$ROOT_PATH/PKGBUILD"
TEMPLATE_PKGBUILD_PATH="$PKGBUILD_FOLDER_PATH/template/template.PKGBUILD"
NEW_PKGBUILD_PLACE="$PKGBUILD_FOLDER_PATH/ligo.PKGBUILD"
LATEST_PKGBUILD_PLACE="$PKBUILD_FOLDER_PATH/ligo.PKGBUILD"

# Place the template to the good place
cp $TEMPLATE_PKGBUILD_PATH $NEW_PKGBUILD_PLACE

# Fill the template which has been placed
./fill_template.sh $NEW_PKGBUILD_PLACE $DEB_PKG_URL $CURRENT_VERSION
