let a : bool = 1 = 1   // equality (true)
let b : bool = 1 <> 0  // inequality (true)
let c : bool = 1 > 0   // greater than (true)
let d : bool = 0 < 1   // lower than (true)
let e : bool = 0 >= 0  // greater than or equal (true)
let f : bool = 0 <= 0  // lower than or equal (true)