name: Check and Build Ligo

on:
  push:
    branches:
      - stable
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - stable

jobs:
  build_nix:
    name: Build Ligo ${{ matrix.system }}
    strategy:
      matrix:
        system: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-ligo-build
          # collect garbage until Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1 GB = 1073741824 B
          gc-max-store-size-linux: 1073741824
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-ligo-build
          # created more than this number of seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never
      - run: nix build -L .#ligo
  format_nix:
    name: Run Formatter on Ligo
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix fmt
